#pragma once

namespace Sonic {

    using Key = uint8_t;

    namespace Keys {

        enum : Key
        {
            // Windows

            Backspace = 0x08,
            Tab = 0x09,
            Clear = 0x0c,
            Enter = 0x0d,
            Shift = 0x10,
            LeftShift = Shift,
            Control = 0x11,
            LeftControl = Control,
            Alt = 0x12,
            LeftAlt = Alt,
            Pause = 0x13,
            CapsLock = 0x14,
            ImeKana = 0x15,
            ImeHangul = 0x15,
            ImeOn = 0x16,
            ImeJunja = 0x17,
            ImeFinal = 0x18,
            ImeHanja = 0x19,
            ImeKanji = 0x19,
            ImeOff = 0x1a,
            Escape = 0x1b,
            ImeConvert = 0x01c,
            ImeNonconvert = 0x1d,
            ImeAccept = 0x1e,
            ImeModeChange = 0x1f,
            Space = 0x20,
            PageUp = 0x21,
            PageDown = 0x22,
            End = 0x23,
            Home = 0x24,
            Left = 0x25,
            ArrowLeft = Left,
            Up = 0x26,
            ArrowUp = Up,
            Right = 0x27,
            ArrowRight = Right,
            Down = 0x28,
            ArrowDown = Down,
            Select = 0x29,
            Print = 0x2a,
            Execute = 0x2b,
            PrintScreen = 0x2c,
            Insert = 0x2d,
            Delete = 0x2e,
            Help = 0x2f,

            _0 = 0x30,
            _1 = 0x31,
            _2 = 0x32,
            _3 = 0x33,
            _4 = 0x34,
            _5 = 0x35,
            _6 = 0x36,
            _7 = 0x37,
            _8 = 0x38,
            _9 = 0x39,

            A = 0x41,
            B = 0x42,
            C = 0x43,
            D = 0x44,
            E = 0x45,
            F = 0x46,
            G = 0x47,
            H = 0x48,
            I = 0x49,
            J = 0x4a,
            K = 0x4b,
            L = 0x4c,
            M = 0x4d,
            N = 0x4e,
            O = 0x4f,
            P = 0x50,
            Q = 0x51,
            R = 0x52,
            S = 0x53,
            T = 0x54,
            U = 0x55,
            V = 0x56,
            W = 0x57,
            X = 0x58,
            Y = 0x59,
            Z = 0x5a,

            Windows = 0x5b,
            LeftWindows = Windows,
            RightWindows = 0x5c,
            Apps = 0x5d,
            Sleep = 0x5f,

            Numpad0 = 0x60,
            Numpad1 = 0x61,
            Numpad2 = 0x62,
            Numpad3 = 0x63,
            Numpad4 = 0x64,
            Numpad5 = 0x65,
            Numpad6 = 0x66,
            Numpad7 = 0x67,
            Numpad8 = 0x68,
            Numpad9 = 0x69,

            Multiply = 0x6a,
            Add = 0x6b,
            Seperator = 0x6c,
            Substract = 0x6d,
            Decimal = 0x6e,
            Divide = 0x6f,

            F1 = 0x70,
            F2 = 0x71,
            F3 = 0x72,
            F4 = 0x73,
            F5 = 0x74,
            F6 = 0x75,
            F7 = 0x76,
            F8 = 0x77,
            F9 = 0x78,
            F10 = 0x79,
            F11 = 0x7a,
            F12 = 0x7b,
            F13 = 0x7c,
            F14 = 0x7d,
            F15 = 0x7e,
            F16 = 0x7f,
            F17 = 0x80,
            F18 = 0x81,
            F19 = 0x82,
            F20 = 0x83,
            F21 = 0x84,
            F22 = 0x85,
            F23 = 0x86,
            F24 = 0x87,

            NumLock = 0x90,
            Scroll = 0x91,

            RightShift = Shift, // They appear to be the same, at least on windows
            // 0xa2 is another left shift?

            RightControl = 0xa3,
            // 0xa2 is another left control?

            RightAlt = 0xa5,
            // 0xa2 is another left alt?

            BrowserBack = 0x46,
            BrowserForward = 0x47,
            BrowserRefresh = 0xa8,
            BrowserStop = 0xa9,
            BrowserSearch = 0xaa,
            BrowserFavorites = 0xab,
            BrowserHome = 0x4c,

            VolumeMute = 0xad,
            VolumeDown = 0x4e,
            VolumeUp = 0xaf,

            MediaNextTrack = 0xb0,
            MediaPreviousTrack = 0xb1,
            MediaStop = 0xb2,
            MediaPlay = 0xb3,
            MediaPause = 0xb3,

            StartMail = 0xb5,
            SelectMedia = 0xb5,
            StartApp1 = 0xb6,
            StartApp2 = 0xb7,
            
            Oem1 = 0xba,

            Plus = 0xbb,
            Comma = 0xbc,
            Minus = 0xbd,
            Period = 0xbe,

            Oem2 = 0xbf,
            Oem3 = 0xc0,
            Oem4 = 0xdb,
            Oem5 = 0xdc,
            Oem6 = 0xdd,
            Oem7 = 0xde,
            Oem8 = 0xdf,
            Oem102 = 0xe2,

            ImeProcess = 0xe5,
            Attn = 0xf6,
            Crsel = 0xf7,
            ExSel = 0xf8,
            EraseEOF = 0xf9,
            Play = 0xfa,
            Zoom = 0xfb,
            PA1 = 0xfd,
            
            OemClear = 0xfe,

   /*         Numpad0 = VK_KP_0,
            Numpad1 = VK_KP_1,
            Numpad2 = VK_KP_2,
            Numpad3 = VK_KP_3,
            Numpad4 = VK_KP_4,
            Numpad5 = VK_KP_5,
            Numpad6 = VK_KP_6,
            Numpad7 = VK_KP_7,
            Numpad8 = VK_KP_8,
            Numpad9 = VK_KP_9,
            NumpadDivide = VK_KP_DIVIDE,
            NumpadMultiply = VK_KP_MULTIPLY,
            NumpadSubstract = VK_KP_SUBTRACT,
            NumpadAdd = VK_KP_ADD,
            NumpadEnter = VK_KP_ENTER,
            NumpadDecimal = VK_KP_DECIMAL,
            NumpadEqualSign = VK_KP_EQUAL,
            Space = VK_SPACE,
            Tab = VK_TAB,
            Up = VK_UP,
            Left = VK_LEFT,
            Down = VK_DOWN,
            Right = VK_RIGHT,
            ControlLeft = VK_LEFT_CONTROL,
            ControlRight = VK_RIGHT_CONTROL,
            ShiftLeft = VK_LEFT_SHIFT,
            ShiftRight = VK_RIGHT_SHIFT,
            AltLeft = VK_LEFT_ALT,
            AltRight = VK_RIGHT_ALT,
            SuperLeft = VK_LEFT_SUPER,
            SuperRight = VK_RIGHT_SUPER,
            CapsLock = VK_CAPS_LOCK,
            Escape = VK_ESCAPE,
            Backspace = VK_BACKSPACE,
            Enter = VK_ENTER,
            Comma = VK_COMMA,
            Period = VK_PERIOD,
            LessThan = VK_WORLD_1,
            Menu = VK_MENU,
            ScrollLock = VK_SCROLL_LOCK,
            Pause = VK_PAUSE,
            Insert = VK_INSERT,
            Delete = VK_DELETE,
            End = VK_END,
            PageUp = VK_PAGE_UP,
            PageDown = VK_PAGE_DOWN,
            NumLock = VK_NUM_LOCK,
            Print = VK_PRINT_SCREEN,

            Qwerty_Apostrophe = VK_APOSTROPHE,
            Qwerty_Semicolon = VK_SEMICOLON,
            Qwerty_BracketLeft = VK_LEFT_BRACKET,
            Qwerty_BracketRight = VK_RIGHT_BRACKET,
            Qwerty_Backslash = VK_BACKSLASH,
            Qwerty_Minus = VK_MINUS,
            Qwerty_EqualSign = VK_EQUAL,
            Qwerty_AccentLeft = VK_GRAVE_ACCENT,
            Qwerty_Slash = VK_SLASH,
            Qwerty_Home = VK_HOME,

            Qwertz_AE = VK_APOSTROPHE,
            Qwertz_OE = VK_SEMICOLON,
            Qwertz_UE = VK_LEFT_BRACKET,
            Qwertz_Plus = VK_RIGHT_BRACKET,
            Qwertz_Hashtag = VK_BACKSLASH,
            Qwertz_Eszett = VK_MINUS,
            Qwertz_AccentRight = VK_EQUAL,
            Qwertz_Circumflex = VK_GRAVE_ACCENT,
            Qwertz_Minus = VK_SLASH,
            Qwertz_Pos1 = VK_HOME*/
        };

    }

}
